export enum ProjectNames {
    AyaRes = 'AyaRes',
    AyaAndCal = 'AyaAndCal',
    CalStateRes = 'CalStateRes',
    CalvinState = 'CalvinState',
    CrisTravis = 'CrisTravis',
    CristinaStLeg = 'CristinaStLeg',
    DelgadoStRes = 'DelgadoStRes',
    EmilyState = 'EmilyState',
    FedCrisTravis = 'FedCrisTravis',
    GopFed = 'GopFed',
    JacobRes = 'JacobRes',
    RiRes = 'RiRes',
    StateLeg = 'StateLeg',
    StateLegCOGA = 'StateLegCOGA',
    TravisRes = 'TravisRes',
    StateHouseRes = 'StateHouseRes',
    BrainRob = 'BrianRob',
    AlList = 'AlList',
    FrankieRes = 'FrankieRes',
    Danyela = 'Danyela'
}